services:
  - type: web
    name: fridaycoms
    runtime: node
    plan: free
    buildCommand: |
      npm install
      cd frontend
      npm install
      npm run build
      cp -r build ../build
    startCommand: "node server.js"
    envVars:
      - key: PASSWORD
        value: Friday123
      - key: NODE_ENV
        value: production
